config/routes.rb
IServe::Application.routes.draw do

  get  'kitchenstaff',              to: 'kitchen_staff_home#index'
  post 'kitchenstaff/itemcomplete', to: 'kitchen_staff_home#itemcomplete'
  post 'kitchenstaff/getnote',      to: 'kitchen_staff_home#getnote'

  get  'waitstaff',                 to: 'wait_staff_home#index'
  post 'waitstaff',                 to: 'wait_staff_home#index'
  post 'waitstaff/vieworders',      to: 'wait_staff_home#vieworders'
  post 'waitstaff/neworder',        to: 'wait_staff_home#neworder'
  post 'waitstaff/saveorder',       to: 'wait_staff_home#saveorder'
  post 'waitstaff/deleteorder',     to: 'wait_staff_home#deleteorder'
  post 'waitstaff/editorder',       to: 'wait_staff_home#editorder'
  get  'waitstaff/editorder',       to: 'wait_staff_home#editorder'

  get  'cashier',                   to: 'cashier_home#index'
  post 'cashier',                   to: 'cashier_home#index'
  post 'cashier/calculatetotal',    to: 'cashier_home#calculatetotal'
  post 'cashier/processpayment',    to: 'cashier_home#processpayment'

  get 'home/index'
  
  get 'management', to: 'admin/management_home#index'
  
  scope :management do
    
    resources :menus, :controller => 'admin/menus'
    
    resources :menu_items, :controller => 'admin/menu_items'   
                   
    resources :customer_order_items, :controller => 'admin/customer_order_items'
                   
    resources :customer_orders, :controller => 'admin/customer_orders'    
                   
    resources :tables, :controller => 'admin/tables'             
                   
    resources :user_types, :controller => 'admin/user_types'
    
    resources :users, :controller => 'users'
    
    resources :user_tables, :controller => 'admin/user_tables'
  end

  devise_for :users

  root 'home#index'

  

end

app/models/customer_order_item.rb
class CustomerOrderItem < ActiveRecord::Base
  belongs_to :customer_order
  belongs_to :menu_item
  
  validates_presence_of :customer_order_id, :menu_item_id
  validates_inclusion_of :is_menu_item_ready, :in => [true, false]
end

app/controllers/admin/customer_order_items_controller.rb
module Admin
  class CustomerOrderItemsController < ManagementHomeController
    before_action :set_customer_order_item, only: [:show, :edit, :update, :destroy]

    # GET /customer_order_items
    # GET /customer_order_items.json
    def index
      @customer_order_items = CustomerOrderItem.all
    end

    # GET /customer_order_items/1
    # GET /customer_order_items/1.json
    def show
    end

    # GET /customer_order_items/new
    def new
      @customer_order_item = CustomerOrderItem.new
    end

    # GET /customer_order_items/1/edit
    def edit
    end

    # POST /customer_order_items
    # POST /customer_order_items.json
    def create
      @customer_order_item = CustomerOrderItem.new(customer_order_item_params)

      respond_to do |format|
        if @customer_order_item.save
          format.html { redirect_to @customer_order_item, notice: 'Customer order item was successfully created.' }
          format.json { render action: 'show', status: :created, location: @customer_order_item }
        else
          format.html { render action: 'new' }
          format.json { render json: @customer_order_item.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /customer_order_items/1
    # PATCH/PUT /customer_order_items/1.json
    def update
      respond_to do |format|
        if @customer_order_item.update(customer_order_item_params)
          format.html { redirect_to @customer_order_item, notice: 'Customer order item was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @customer_order_item.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /customer_order_items/1
    # DELETE /customer_order_items/1.json
    def destroy
      @customer_order_item.destroy
      respond_to do |format|
        format.html { redirect_to customer_order_items_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_customer_order_item
        @customer_order_item = CustomerOrderItem.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def customer_order_item_params
        params.require(:customer_order_item).permit(:customer_order_id, :menu_item_id, :is_menu_item_ready, :waitstaff_note)
      end
  end
  
end

app/helpers/customer_order_items_helper.rb
module CustomerOrderItemsHelper
end

app/views/admin/customer_order_items/_form.html.erb
<%= form_for @customer_order_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :customer_order_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_order_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :menu_item_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :menu_item_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_menu_item_ready, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :is_menu_item_ready, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :waitstaff_note, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :waitstaff_note, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customer_order_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/customer_order_items/edit.html.erb
<%- model_class = CustomerOrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/customer_order_items/index.html.erb
<%- model_class = CustomerOrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customer_order_id) %></th>
      <th><%= model_class.human_attribute_name(:menu_item_id) %></th>
      <th><%= model_class.human_attribute_name(:is_menu_item_ready) %></th>
      <th><%= model_class.human_attribute_name(:waitstaff_note) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customer_order_items.each do |customer_order_item| %>
      <tr>
        <td><%= link_to customer_order_item.id, customer_order_item_path(customer_order_item) %></td>
        <td><%= customer_order_item.customer_order_id %></td>
        <td><%= customer_order_item.menu_item_id %></td>
        <td><%= customer_order_item.is_menu_item_ready %></td>
        <td><%= customer_order_item.waitstaff_note %></td>
        <td><%=l customer_order_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_order_item_path(customer_order_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_order_item_path(customer_order_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_order_item_path,
            :class => 'btn btn-primary' %>

app/views/admin/customer_order_items/new.html.erb
<%- model_class = CustomerOrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/customer_order_items/show.html.erb
<%- model_class = CustomerOrderItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer_order_id) %>:</strong></dt>
  <dd><%= @customer_order_item.customer_order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:menu_item_id) %>:</strong></dt>
  <dd><%= @customer_order_item.menu_item_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_menu_item_ready) %>:</strong></dt>
  <dd><%= @customer_order_item.is_menu_item_ready %></dd>
  <dt><strong><%= model_class.human_attribute_name(:waitstaff_note) %>:</strong></dt>
  <dd><%= @customer_order_item.waitstaff_note %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customer_order_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_order_item_path(@customer_order_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_order_item_path(@customer_order_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>