config/routes.rb
IServe::Application.routes.draw do

  get  'kitchenstaff',              to: 'kitchen_staff_home#index'
  post 'kitchenstaff/itemcomplete', to: 'kitchen_staff_home#itemcomplete'
  post 'kitchenstaff/getnote',      to: 'kitchen_staff_home#getnote'

  get  'waitstaff',                 to: 'wait_staff_home#index'
  post 'waitstaff',                 to: 'wait_staff_home#index'
  post 'waitstaff/vieworders',      to: 'wait_staff_home#vieworders'
  post 'waitstaff/neworder',        to: 'wait_staff_home#neworder'
  post 'waitstaff/saveorder',       to: 'wait_staff_home#saveorder'
  post 'waitstaff/deleteorder',     to: 'wait_staff_home#deleteorder'
  post 'waitstaff/editorder',       to: 'wait_staff_home#editorder'
  get  'waitstaff/editorder',       to: 'wait_staff_home#editorder'

  get  'cashier',                   to: 'cashier_home#index'
  post 'cashier',                   to: 'cashier_home#index'
  post 'cashier/calculatetotal',    to: 'cashier_home#calculatetotal'
  post 'cashier/processpayment',    to: 'cashier_home#processpayment'

  get 'home/index'
  
  get 'management', to: 'admin/management_home#index'
  
  scope :management do
    
    resources :menus, :controller => 'admin/menus'
    
    resources :menu_items, :controller => 'admin/menu_items'   
                   
    resources :customer_order_items, :controller => 'admin/customer_order_items'
                   
    resources :customer_orders, :controller => 'admin/customer_orders'    
                   
    resources :tables, :controller => 'admin/tables'             
                   
    resources :user_types, :controller => 'admin/user_types'
    
    resources :users, :controller => 'users'
    
    resources :user_tables, :controller => 'admin/user_tables'
  end

  devise_for :users

  root 'home#index'

  

end

app/models/customer_order.rb
class CustomerOrder < ActiveRecord::Base
  belongs_to :table
  has_many :customer_order_items
  has_many :menu_items, through: :customer_order_items
  
  validates_presence_of :table_id
  validates_inclusion_of :is_order_ready, :in => [true, false]
  validates_inclusion_of :is_order_paid_for, :in => [true, false]
end

app/models/customer_order_item.rb
class CustomerOrderItem < ActiveRecord::Base
  belongs_to :customer_order
  belongs_to :menu_item
  
  validates_presence_of :customer_order_id, :menu_item_id
  validates_inclusion_of :is_menu_item_ready, :in => [true, false]
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_many :customer_order_items
  has_many :customer_orders, through: :customer_order_items
  belongs_to :menu
  
  validates_presence_of :item_name, :item_price, :menu_id
  validates_numericality_of :item_price, :greater_than => 0
end

app/models/table.rb
class Table < ActiveRecord::Base
  has_many :customer_orders

  has_many :employee_tables
  has_many :employees, through: :employee_tables

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :user_type
  has_many :user_tables
  has_many :tables, through: :user_tables
end

app/models/user_table.rb
class UserTable < ActiveRecord::Base
  belongs_to :user
  belongs_to :table
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin/user_types_controller.rb
module Admin
  class UserTypesController < ManagementHomeController
    before_action :set_user_type, only: [:show, :edit, :update, :destroy]

    # GET /user_types
    # GET /user_types.json
    def index
      @user_types = UserType.all
    end

    # GET /user_types/1
    # GET /user_types/1.json
    def show
    end

    # GET /user_types/new
    def new
      @user_type = UserType.new
    end

    # GET /user_types/1/edit
    def edit
    end

    # POST /user_types
    # POST /user_types.json
    def create
      @user_type = UserType.new(user_type_params)

      respond_to do |format|
        if @user_type.save
          format.html { redirect_to @user_type, notice: 'User type was successfully created.' }
          format.json { render action: 'show', status: :created, location: @user_type }
        else
          format.html { render action: 'new' }
          format.json { render json: @user_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /user_types/1
    # PATCH/PUT /user_types/1.json
    def update
      respond_to do |format|
        if @user_type.update(user_type_params)
          format.html { redirect_to @user_type, notice: 'User type was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user_types/1
    # DELETE /user_types/1.json
    def destroy
      @user_type.destroy
      respond_to do |format|
        format.html { redirect_to user_types_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user_type
        @user_type = UserType.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_type_params
        params.require(:user_type).permit(:type_name)
      end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if    current_user.user_type_id == 1
        redirect_to management_path
      elsif current_user.user_type_id == 2
        redirect_to waitstaff_path
      elsif current_user.user_type_id == 3
        redirect_to cashier_path
      elsif current_user.user_type_id == 4
        redirect_to kitchenstaff_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :is_authorized

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:id => :asc)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :user_type_id, :password, :password_confirmation)
  end

  def is_authorized
    if ![1].include?(current_user.user_type_id)
      flash[:error] = 'Not authorized to view this resource.'
      redirect_to :root
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashier_home_helper.rb
module CashierHomeHelper
end

app/helpers/customer_orders_helper.rb
module CustomerOrdersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/management_home_helper.rb
module ManagementHomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/user_tables_helper.rb
module UserTablesHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/user_types/_form.html.erb
<%= form_for @user_type, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :type_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :type_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/user_types/edit.html.erb
<%- model_class = UserType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/user_types/index.html.erb
<%- model_class = UserType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:type_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_types.each do |user_type| %>
      <tr>
        <td><%= link_to user_type.id, user_type_path(user_type) %></td>
        <td><%= user_type.type_name %></td>
        <td><%=l user_type.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_type_path(user_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_type_path(user_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_type_path,
            :class => 'btn btn-primary' %>

app/views/admin/user_types/new.html.erb
<%- model_class = UserType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/user_types/show.html.erb
<%- model_class = USerType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:type_name) %>:</strong></dt>
  <dd><%= @user_type.type_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_type_path(@user_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_type_path(@user_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>