config/routes.rb
IServe::Application.routes.draw do

  get  'kitchenstaff',              to: 'kitchen_staff_home#index'
  post 'kitchenstaff/itemcomplete', to: 'kitchen_staff_home#itemcomplete'
  post 'kitchenstaff/getnote',      to: 'kitchen_staff_home#getnote'

  get  'waitstaff',                 to: 'wait_staff_home#index'
  post 'waitstaff',                 to: 'wait_staff_home#index'
  post 'waitstaff/vieworders',      to: 'wait_staff_home#vieworders'
  post 'waitstaff/neworder',        to: 'wait_staff_home#neworder'
  post 'waitstaff/saveorder',       to: 'wait_staff_home#saveorder'
  post 'waitstaff/deleteorder',     to: 'wait_staff_home#deleteorder'
  post 'waitstaff/editorder',       to: 'wait_staff_home#editorder'
  get  'waitstaff/editorder',       to: 'wait_staff_home#editorder'

  get  'cashier',                   to: 'cashier_home#index'
  post 'cashier',                   to: 'cashier_home#index'
  post 'cashier/calculatetotal',    to: 'cashier_home#calculatetotal'
  post 'cashier/processpayment',    to: 'cashier_home#processpayment'

  get 'home/index'
  
  get 'management', to: 'admin/management_home#index'
  
  scope :management do
    
    resources :menus, :controller => 'admin/menus'
    
    resources :menu_items, :controller => 'admin/menu_items'   
                   
    resources :customer_order_items, :controller => 'admin/customer_order_items'
                   
    resources :customer_orders, :controller => 'admin/customer_orders'    
                   
    resources :tables, :controller => 'admin/tables'             
                   
    resources :user_types, :controller => 'admin/user_types'
    
    resources :users, :controller => 'users'
    
    resources :user_tables, :controller => 'admin/user_tables'
  end

  devise_for :users

  root 'home#index'

  

end

app/models/customer_order.rb
class CustomerOrder < ActiveRecord::Base
  belongs_to :table
  has_many :customer_order_items
  has_many :menu_items, through: :customer_order_items
  
  validates_presence_of :table_id
  validates_inclusion_of :is_order_ready, :in => [true, false]
  validates_inclusion_of :is_order_paid_for, :in => [true, false]
end

app/controllers/admin/customer_orders_controller.rb
module Admin
  class CustomerOrdersController < ManagementHomeController
    before_action :set_customer_order, only: [:show, :edit, :update, :destroy]

    # GET /customer_orders
    # GET /customer_orders.json
    def index

      @customer_orders = CustomerOrder.all.order(['table_id asc', 'id asc'])

      if params[:filter] && params[:filter] == "true"
        @customer_orders = @customer_orders.where(:is_order_ready => false)
      end

    end

    # GET /customer_orders/1
    # GET /customer_orders/1.json
    def show
    end

    # GET /customer_orders/new
    def new
      @customer_order = CustomerOrder.new
    end

    # GET /customer_orders/1/edit
    def edit
    end

    # POST /customer_orders
    # POST /customer_orders.json
    def create
      @customer_order = CustomerOrder.new(customer_order_params)

      respond_to do |format|
        if @customer_order.save
          format.html { redirect_to @customer_order, notice: 'Customer order was successfully created.' }
          format.json { render action: 'show', status: :created, location: @customer_order }
        else
          format.html { render action: 'new' }
          format.json { render json: @customer_order.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /customer_orders/1
    # PATCH/PUT /customer_orders/1.json
    def update
      respond_to do |format|
        if @customer_order.update(customer_order_params)
          format.html { redirect_to @customer_order, notice: 'Customer order was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @customer_order.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /customer_orders/1
    # DELETE /customer_orders/1.json
    def destroy
      @customer_order.destroy
      respond_to do |format|
        format.html { redirect_to customer_orders_url }
        format.json { head :no_content }
      end
    end

    #Filter for showing only order that aren't ready
    def filter
      @customer_orders = CustomerOrder.all.order(['table_id asc', 'id asc'])
      redirect_to customer_orders_path
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_customer_order
        @customer_order = CustomerOrder.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def customer_order_params
        params.require(:customer_order).permit(:table_id, :is_order_ready, :is_order_paid_for)
      end
  end
end

app/helpers/customer_orders_helper.rb
module CustomerOrdersHelper
end

app/views/admin/customer_orders/_form.html.erb
<%= form_for @customer_order, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :table_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :table_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_order_ready, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :is_order_ready, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_order_paid_for, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :is_order_paid_for, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customer_orders_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/customer_orders/edit.html.erb
<%- model_class = CustomerOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/customer_orders/index.html.erb
<%- model_class = CustomerOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:table_id) %></th>
      <th><%= model_class.human_attribute_name(:is_order_ready) %></th>
      <th><%= model_class.human_attribute_name(:is_order_paid_for) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customer_orders.each do |customer_order| %>
      <tr>
        <td><%= link_to customer_order.id, customer_order_path(customer_order) %></td>
        <td><%= customer_order.table_id %></td>
        <td><%= customer_order.is_order_ready %></td>
        <td><%= customer_order.is_order_paid_for %></td>
        <td><%=l customer_order.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_order_path(customer_order), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_order_path(customer_order),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_order_path,
            :class => 'btn btn-primary' %>

app/views/admin/customer_orders/new.html.erb
<%- model_class = CustomerOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/customer_orders/show.html.erb
<%- model_class = CustomerOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:table_id) %>:</strong></dt>
  <dd><%= @customer_order.table_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_order_ready) %>:</strong></dt>
  <dd><%= @customer_order.is_order_ready %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_order_paid_for) %>:</strong></dt>
  <dd><%= @customer_order.is_order_paid_for %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customer_orders_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_order_path(@customer_order), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_order_path(@customer_order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>